### ISSUE TITLE
example tag displayed

### ISSUE THREAD

**Issue by DylanKojiCheslin** [DylanKojiCheslin/indexCards2#3]
- [x] meteor add babrahams:constellation #4
- [x] create model for a tag #5
- [x] at startup populate Tag with an example #6
- [ ] display list of tags on "/" page #7
